package com.example.demo;
class AccountController {
    private Account model;
    private AccountView view;
    private User user;
    private Accountant accountant;

    AccountController(Account model, AccountView view) {
        this.model = model;
        this.view = view;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public void setAccountant(Accountant accountant) {
        this.accountant = accountant;
    }

    public void generateEStatement() {
        // Check if both user and accountant are set
        if (user == null || accountant == null) {
            System.out.println("User or accountant not set. Cannot generate e-statement.");
            return;
        }

        // Generate e-statement
        System.out.println("E-Statement for " + model.getName());
        System.out.println("Requested by: " + user.getName());
        System.out.println("Generated by: " + accountant.getName());
        view.display(model.getName(), model.getCNIC(), model.getAccountNumber(), model.getAccountType());
    }
}